[package]
name = "math"
version = "0.1.0"
entrypoint = "header.typ"
description = "A really simple package to correctly format math courses. Created for my own usecase at school"
authros = ["Kuci Elvin <elvin.kuci@hotmail.com>"]
license = "MIT"

